### ISSUE TITLE
Cannot find "next" function

### ISSUE THREAD

**Issue by jiyizhezhang** [Alaleh/PDBO#1]
Hi, 
Thanks for sharing this diversity driven algorithm! 
I tried to run the code but just got one question:
In the main.py file, there is a function called "next", but I cannot find a function related to that, could you please help me with this? Many thanks!

The original code in main.py:
"for _ in range(args.n_iter):
        X_next, Y_next = next(solution)
        exporter.update(X_next, Y_next)
        exporter.write_csvs()"

Best regards,
Jz

**Comment by Alaleh** [comment]
Hi Jz, 
The next() function is a Python method that returns the next item in an iterator. Please, see [here](https://www.w3schools.com/python/ref_func_next.asp) for more info!
